account/urls.py
from django.conf.urls import patterns, include, url

urlpatterns = patterns('',
    url(r'^login/$', 'django.contrib.auth.views.login',
            {'template_name': 'account/login.html'}, name='login'),
    url(r'^logout/$', 'django.contrib.auth.views.logout',
            {'next_page': 'home'}, name='logout'),
    url(r'^register/$', 'account.views.register', name='register'),
    url(r'^(?P<pk>\d+)/', 'account.views.shortcut', name='shortcut'),
    url(r'^(?P<username>\w+)/$', 'account.views.user_view', name='userview'),
)

agora/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
# for dev only:
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = patterns('',
    url(r'^$',  'agora.views.home', name='home'),
    url(r'^s/', 'agora.views.search', name='search'),
    url(r'^a/', include('listing.urls', namespace='listing')),
    url(r'^p/(?P<pk>\d+)/', include('proposal.urls', namespace='proposal')),
    url(r'^l/(?P<place>\d+)/', include('place.urls', namespace='place')),
    url(r'^t/(?P<tag>\d+)/', include('tag.urls', namespace='tag')),
    url(r'^u/', include('account.urls', namespace='account')),
    url(r'^g/', include('germ.urls', namespace='germ')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^markdown/$', 'synopsis.views.markdown', name='markdown'),
    url(r'^m/$', 'django_markdown.views.preview', name='django_markdown_preview')
) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

germ/urls.py
from django.conf.urls import patterns, url

urlpatterns = patterns('germ.views',
    url(r'^$', 'list', name='list'),
    url(r'^new/', 'new', name='new'),
    url(r'^(?P<pk>\d+)/', 'edit', name='edit')
)

listing/urls.py
from django.conf.urls import patterns, url

urlpatterns = patterns('listing.views',
    url(r'^$', 'standard', name='standard'))

tag/urls.py
from django.conf.urls import patterns, url

urlpatterns = patterns('tag.views',
    url(r'^(?P<slug>[-\w]+)/$', 'list', name='list'),
    url(r'^$', 'shortcut', name='shortcut'),
)

agora/models.py
from django.db import models
from django.contrib.auth.models import User

class DeletedReason(models.Model):
    # 'charter'
    # 'spam'
    # 'double'
    # 'other'
    label = models.CharField(
        primary_key     = True,
        max_length      = 7)

    def __str__(self):
        return self.label

class DeletedContent(models.Model):
    reason = models.ForeignKey(
        to              = DeletedReason)

    user = models.ForeignKey(
        to              = User)

    date = models.DateTimeField(
        auto_now_add    = True)

agora/forms.py
from django import forms
from django.utils.translation import ugettext_lazy as _
import logging

logger = logging.getLogger(__name__)

class ModifyForm(forms.Form):
    message = forms.CharField(
        error_messages  = {
        'required': _("Enter a reason for the change"),
        'min_length':
         _("The reason for the change is too short (10 characters minimum)."),
        'max_length':
        _("The reason for the change is too long (1000 characters maximum).")},
        min_length      = 10,
        max_length      = 1000,
        required        = True,
        widget          = forms.Textarea({
        'placeholder': _("Reason for change (10 characters minimum)"),
        'cols': 40,
        'rows': 4 }))

    def clean_message(self):
        t = self.cleaned_data.get('message')
        t = " ".join(t.split())
        t = t.strip()
        if t == '':
            raise forms.ValidationError(_("Enter a valid reason."))
        return t

agora/views.py
from django.shortcuts import render
from django.http import HttpResponseBadRequest
from haystack.forms import SearchForm
from haystack.query import SearchQuerySet
from proposal.models import Proposal
from tag.models import Tag
from place.models import GenericPlace
import listing.views
import pdb
from django import forms
from django.utils.translation import ugettext as _

def searchform(request):
    f = SearchForm(initial = {'models': {
                        'place.genericplace': True,
                        'tag.tag': True,
                        'proposal.proposal': True }})
    f.fields['q'].widget.attrs['placeholder'] = _('search')
    f.fields['q'].widget.attrs['size'] = 30
    return f

def search(request):
    f = SearchForm(request.GET)
    if not f.is_valid():
        return HttpResponseBadRequest("Bad request")

    r = SearchQuerySet().filter(content=request.GET.get('q'))
    pr = []
    for s in r.models(GenericPlace):
        pr.extend([ p for p in Proposal.objects.filter(place=s.object) ])
    for s in r.models(Tag):
        pr.extend([ p for p in Proposal.objects.filter(tags=s.object) ])
    pr.extend([ s.object for s in r.models(Proposal) ])
    return listing.views.list_search(request, pr)

def home(request):
    searchbox = searchform(request)
    return render(request, 'agora/home.html', locals())

agora/templates/agora/content.html
{% extends "agora/home.html" %}

{% block content %}
content
{% endblock %}

agora/templates/agora/flat.html
<div><h1>title</h1></div>
<div id="content">
    {% block content %}
    {% endblock %}
</div>

agora/templates/agora/flat_popup.html
{% extends "agora/home.html" %}

{% block content %}

<h3>{% block popup_title %}invalid: flat_popup title{% endblock %}</h3>
<h4>{% block popup_subtitle %}invalid: flat_popup subtitle{% endblock %}</h4>
<h5>{% block popup_subsubtitle %}invalid: flat_popup subsubtitle{% endblock %}</h4>

<div>{% block popup_content %}invalid: flat_popup content{% endblock %}</div>

<p><a href="{% block popup_close %}invalid: flat_popup close{% endblock %}">return</a></p>

{% endblock %}

agora/templates/agora/home.html
<div><h1>title</h1></div>
<div id="top">
    {% include 'search/searchbox.html' %}
</div>
<div id="menu_global">
    <h2>global menu</h2>
    {% if user.is_authenticated %}
        <a href="{% url 'account:userview' username=user.username %}">{{ user.username }}</a>
        (<a href="{% url 'account:logout' %}">logout</a>)<br>
    {% else %}
        <a href="{% url 'account:register' %}">register</a><br>
        <a href="{% url 'account:login' %}">login</a><br>
    {% endif %}
    <a href="{% url 'listing:standard' %}">listing</a><br>
    {% if user.is_authenticated %}
        <a href="{% url 'listing:standard' %}?pi={{ user.account.place.pk }}">local</a><br>
        <a href="{% url 'listing:standard' %}?uu={{ user.pk }}">undecided</a><br>
        <a href="{% url 'listing:standard' %}?uf={{ user.pk }}">in favor</a><br>
        <a href="{% url 'listing:standard' %}?ua={{ user.pk }}">cons</a><br>
        <a href="{% url 'germ:list' %}">germs</a><br>
    {% endif %}
    <a href="{% url 'germ:new' %}">new germ</a><br>
</div>
{% comment %}
<div id="menu_context">
    <h2>contextual menu</h2>
</div>
{% endcomment %}
<hr>
<div id="content">
    {% block content %}
    <h2>content</h2>
    <span>no content</span>
    {% endblock %}
</div>

agora/templates/agora/list.html
{% extends "agora/home.html" %}

{% block content %}
list container
{% endblock %}

agora/templates/agora/popup.html
{% block content %}
popup
{% endblock %}