agora/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
# for dev only:
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = patterns('',
    url(r'^$',  'agora.views.home', name='home'),
    url(r'^s/', 'agora.views.search', name='search'),
    url(r'^a/', include('listing.urls', namespace='listing')),
    url(r'^p/(?P<pk>\d+)/', include('proposal.urls', namespace='proposal')),
    url(r'^l/(?P<place>\d+)/', include('place.urls', namespace='place')),
    url(r'^t/(?P<tag>\d+)/', include('tag.urls', namespace='tag')),
    url(r'^u/', include('account.urls', namespace='account')),
    url(r'^g/', include('germ.urls', namespace='germ')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^markdown/$', 'synopsis.views.markdown', name='markdown'),
    url(r'^m/$', 'django_markdown.views.preview', name='django_markdown_preview')
) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

germ/urls.py
from django.conf.urls import patterns, url

urlpatterns = patterns('germ.views',
    url(r'^$', 'list', name='list'),
    url(r'^new/', 'new', name='new'),
    url(r'^(?P<pk>\d+)/', 'edit', name='edit')
)

tag/urls.py
from django.conf.urls import patterns, url

urlpatterns = patterns('tag.views',
    url(r'^(?P<slug>[-\w]+)/$', 'list', name='list'),
    url(r'^$', 'shortcut', name='shortcut'),
)

germ/models.py
from django.contrib.auth.models import User
from django.utils import timezone
from django.db import models
from django.utils.translation import ugettext_lazy as _
from unidecode import unidecode
from place.models import GenericPlace
import logging

logger = logging.getLogger(__name__)

class Germ(models.Model):
    title = models.CharField(
        verbose_name    = _('title'),
        max_length      = 140,
        unique          = False,
        blank           = False,
        null            = False,
        help_text       = _('title'))

    creator = models.ForeignKey(
        to              = User,
        related_name    = 'germCreatorOf',
        editable        = False) # hide from admin and form

# SHOULD GO TO LOGS ONLY
#    verifiers = models.ManyToManyField(
#        to              = User,
#        through         = 'Verifier',
#        editable        = False) # hide from admin and form

    version = models.IntegerField(
        verbose_name    = _('version of the proposal'),
        editable        = False, # hide from admin and form
        default         = 0,
        help_text       = _('autopopulated'))

    place = models.ForeignKey(GenericPlace)

    def save(self, *args, **kwargs):
        if not self.id:
            # newly created object
            self.title = self.title[0:1].capitalize() + self.title[1:]

        self.full_clean()
        return super(Germ, self).save(*args, **kwargs)

    class Meta:
        verbose_name = _('germ')
        verbose_name_plural = _('germs')

    def __str__(self):
        return self.title

germ/forms.py
from django.core.exceptions import ObjectDoesNotExist
from django.utils.translation import ugettext_lazy as _
from germ.models import Germ
from django import forms
from django.contrib.contenttypes.models import ContentType
import place.models
import logging
#import pdb; pdb.set_trace()

logger = logging.getLogger(__name__)

class NewGermForm(forms.Form):
    germ_id = forms.IntegerField(
            widget          = forms.HiddenInput())

    title = forms.CharField(
            label           = _("Title (10 to 140 characters)"),
            error_messages  = {'required':   _("Please choose a title."),
                               'min_length': _("The title is too short (10 characters min)."),
                               'max_length': _("The title is too long (140 characters max).")},
            min_length      = 10,
            max_length      = 140,
            help_text       = _("Choose wisely TODO"),
            required = True)

    place = forms.CharField(
            label           = _("Enter place, or city postcode"),
            max_length      = 50,
            required        = False)

    legit = forms.BooleanField(
            label           = _("The new proposal respects the legislation in place"),
            error_messages  = {'required': _("Please confirm the legislation is respected.")},
            help_text       = _("Avoid insulting, agressive or derogatory elements"),
            required        = True)

    etiquette = forms.BooleanField(
            label           = _("The new proposal respects the site etiquette"),
            error_messages  = {'required': _("Please confirm the etiquette is respected.")},
            help_text       = _("Use correct, simple and concise language"),
            required        = True)

    binary = forms.BooleanField(
            label           = _("One can vote for/against the new proposal"),
            error_messages  = {'required': _("Please confirm the proposal can be polled.")},
            help_text       = _('Formulate the title in a way that someone can say "I agree" or "I disagree" with this'),
            required        = True)

    def clean_title(self):
        t = self.cleaned_data.get('title')
        t = " ".join(t.split())
        t = t.strip()
        if t == '':
            logger.info("trying to enter an empty title")
            raise forms.ValidationError(_("Please enter a valid title."))
        if len(t) < 10:
            logger.info("trying to enter a title with less than 10 characters")
            raise forms.ValidationError(_("Please enter a longer title."))
        return t

    def clean_place(self):
        t = self.cleaned_data.get('place')
        t = " ".join(t.split())
        t = t.strip()
        if t == '':
            raise forms.ValidationError(_("Please enter a place."))
        l = place.models.clean_place(t)
        c = len(l)
        if c == 0:
            raise forms.ValidationError(_("No matching place was found, please check."))
        elif c > 1:
            raise forms.ValidationError(_("Multiple matches, please specify."))
        else:
            t = l[0]
            self.data['place'] = t
        return t

    class Meta:
        model = Germ

germ/views.py
from django.shortcuts import render, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from germ.models import Germ
from germ.forms import NewGermForm
from django.http import HttpResponseRedirect
from django.core.urlresolvers import reverse
from django.utils.translation import ugettext as _
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from place.views import get_breadcrumbs
from django.views.defaults import server_error
from django.contrib.contenttypes.models import ContentType
from place.models import *
import logging
#import pdb; pdb.set_trace()

logger = logging.getLogger(__name__)

def save(form, user):
    pk = form.cleaned_data['germ_id']
    if pk == 0:
        g = Germ()
        g.creator = user
        g.version = 0
    else:
        g = get_object_or_404(Germ, pk=pk)
        g.version += 1
    g.title = form.cleaned_data['title']
    g.place = GenericPlace.objects.get(label=form.cleaned_data['place'])
    g.save()

@login_required
def new(request):
    if request.method == 'POST':
        i = request.POST.copy()
        form = NewGermForm(i)
        if 'validate' in request.POST:
            if form.is_valid():
                return HttpResponseRedirect(reverse('home'))

        elif 'save' in request.POST:
            if form.is_valid():
                save(form, request.user)
                return HttpResponseRedirect(reverse('germ:list'))

        else:
            return HttpResponseRedirect(reverse('home'))

        # if here, validation has failed, reset confim boxes
        if 'legit' in form.data: del form.data['legit']
        if 'etiquette' in form.data: del form.data['etiquette']
        if 'binary' in form.data: del form.data['binary']

    else:
        form = NewGermForm(initial={'germ_id': 0})

    return render(request, 'germ/edit.html', locals())

@login_required
def list(request):
    ps = Germ.objects.filter(creator = request.user)
    #u = request.user
    pg = Paginator(ps, 10)
    page = request.GET.get('page')

    try:
        pr = pg.page(page)
    except PageNotAnInteger:
        # If page is not an integer, deliver first page.
        pr = pg.page(1)
    except EmptyPage:
        # If page is out of range (e.g. 9999), deliver last page of results.
        pr = pg.page(pg.num_pages)

    ts = [ {'proposal': p,
            #'status': get_status(p, u),
            'breadcrumbs': get_breadcrumbs(p.place) } for p in pr ]
    return render(request, 'germ/list.html', locals())

@login_required
def edit(request, pk):
    g = get_object_or_404(Germ, pk=pk)
    if g.creator != request.user:
        return HttpResponseRedirect(reverse('germ:list'))

    form = NewGermForm(initial = { 'germ_id': pk,
                                   'title': g.title,
                                   'place': g.place })
    return render(request, 'germ/edit.html', locals())

germ/templates/germ/edit.html
{% extends 'agora/content.html' %}
{% block content %}

{% load i18n %}

<div>
    <form action="{% url 'germ:new' %}" method="post" novalidate>
        {% csrf_token %}
        <fieldset>
            <h1>{% trans "Create a proposal" %}</h1>
            {{ form.germ_id }}
        </fieldset>
        <fieldset>
            <p>
                {{ form.title.label }}<br>{{ form.title }}<br>
                {{ form.title.errors }}<br>
           </p>
            <p>
                {{ form.place.label }}<br>
                {{ form.place }}
                <br>{{ form.place.errors }}
           </p>
        </fieldset>
        <fieldset>
            <p>
                {{ form.legit }}{{ form.legit.label }}<br>
                {{ form.legit.help_text }}
                <br>{{ form.legit.errors }}
            </p>
            <p>
                {{ form.etiquette }}{{ form.etiquette.label }}<br>
                {{ form.etiquette.help_text }}
                <br>{{ form.etiquette.errors }}
            </p>
            <p>
                {{ form.binary }}{{ form.binary.label }}<br>
                {{ form.binary.help_text }}
                <br>{{ form.binary.errors }}
            </p>
            <p>(peers will be asked to answer the same questions during the validation phase)</p>
        </fieldset>
        <fieldset>
            <input type="submit" name="validate" value="{% trans "The proposal is ready! Send for peer validation" %}"/>
            <input type="submit" name="save" value="{% trans "save for later" %}"/>
            <input type="submit" name="cancel" value="{% trans "cancel" %}"/>
        </fieldset>
    </form>
    <div id="notes">
        <p>The title of your proposal cannot change once validated by peers. You will be able to add content, tags, relations and more, after this initial validation phase. Once validated, your proposal will be visible to all. You will however keep full control over it, until you select moderators to help you develop your idea, or even decide to open selected fields to the public.</p>
    </div>
</div>

{% endblock %}

germ/templates/germ/list.html
{% extends 'agora/list.html' %}
{% block content %}

{% load i18n %}
{% load usertags %}

<div class="p_list">
    {% if not ps %}
        <span class="p_empty_list">{% trans "There are no germs." %}</span>
    {% else %}
        <ul>
        {% for t in ts %}
            {% with p=t.proposal breadcrumbs=t.breadcrumbs %}
                <li><div class="p_card">
                    <div class="p_frame">
                        <div class="p_picture">
                        </div>
                        <div class="p_place">
                            {% include 'place/breadcrumb.html' %}
                        </div>
                        <div class="p_title">
                            <h3>{{ p.title }}</h3>
                        </div>
                        <div class="p_tags">
                            {% include 'proposal/tags.html' %}
                        </div>
                        <div class="p_menu">
                            {% include 'germ/menu.html' %}
                        </div>
                    </div>
                </div></li>
            {% endwith %}
        {% endfor %}
        </ul>
    {% endif %}
</div>

{% endblock %}

germ/templates/germ/menu.html
{% load i18n %}

<ul>
    <li>
        <a href="{% url 'germ:edit' pk=p.pk %}">
            {% trans "edit" %}
        </a>
    </li>
    <li>
        {% trans "send for validation" %}
    </li>
    <li>
        {% trans "delete" %}
    </li>
</ul>