agora/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
# for dev only:
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = patterns('',
    url(r'^$',  'agora.views.home', name='home'),
    url(r'^s/', 'agora.views.search', name='search'),
    url(r'^a/', include('listing.urls', namespace='listing')),
    url(r'^p/(?P<pk>\d+)/', include('proposal.urls', namespace='proposal')),
    url(r'^l/(?P<place>\d+)/', include('place.urls', namespace='place')),
    url(r'^t/(?P<tag>\d+)/', include('tag.urls', namespace='tag')),
    url(r'^u/', include('account.urls', namespace='account')),
    url(r'^g/', include('germ.urls', namespace='germ')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^markdown/$', 'synopsis.views.markdown', name='markdown'),
    url(r'^m/$', 'django_markdown.views.preview', name='django_markdown_preview')
) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

proposal/urls.py
from django.conf.urls import patterns, include, url

urlpatterns_slug = patterns('proposal.views',
    url(r'^$', 'content', name='content'),
    url(r'^d/$', 'discuss', name='discuss'),
    url(r'^r/$', 'reference', name='reference'),
    url(r'^s/$', 'statistics', name='statistics'),
    url(r'^c/$', 'charter', name='charter'),
    url(r'^h/', include('synopsis.urls', namespace='synopsis')),
    url(r'^t/', include('tag.urls_proposal', namespace='tag')),
    url(r'^i/', include('cover.urls', namespace='cover')))

urlpatterns = patterns('proposal.views',
    url(r'^(?P<slug>[-\w]+)/', include(urlpatterns_slug)),
    url(r'^$', 'shortcut', name='shortcut'))

tag/urls.py
from django.conf.urls import patterns, url

urlpatterns = patterns('tag.views',
    url(r'^(?P<slug>[-\w]+)/$', 'list', name='list'),
    url(r'^$', 'shortcut', name='shortcut'),
)

proposal/models.py
from django.contrib.auth.models import User
from django.utils import timezone
from django.db import models
from django.utils.translation import ugettext_lazy as _
from django.template.defaultfilters import slugify
from unidecode import unidecode
from place.models import GenericPlace
from synopsis.models import Synopsis
from tag.models import Tag
import logging
from cover.models import Cover
#import pdb; pdb.set_trace()

logger = logging.getLogger(__name__)

class Proposal(models.Model):
    title = models.CharField(
        verbose_name    = _('title'),
        max_length      = 140,
        unique          = False,
        blank           = False,
        null            = False,
        help_text       = _('title'))

    synopsis_root = models.OneToOneField(
        to              = Synopsis,
        related_name    = 'synopsis_root_of')

    synopsis = models.OneToOneField(
        to              = Synopsis,
        related_name    = 'synopsis_of')

    creator = models.ForeignKey(
        to              = User,
        related_name    = 'creatorOf',
        editable        = False) # hide from admin and form

    #verifiers = models.ManyToManyField(
    # SHOULD BE IN LOG ONLY, WITH DATE AND USER

    cover_root = models.OneToOneField(
        to              = Cover,
        related_name    = 'cover_root_of')

    cover = models.OneToOneField(
        to              = Cover,
        related_name    = 'cover_of')

    place = models.ForeignKey(GenericPlace)

#    affiliate = models.CharField(
#        verbose_name    = _('charity affiliate'),
#        max_length      = 20,
#        unique          = False,
#        help_text       = _('charity affiliate'))

    slug = models.SlugField(
        verbose_name    = _('slug'),
        max_length      = 140,
        blank           = False,
        null            = False,
        editable        = False, # hide from admin and form
        help_text       = _('autogenerated, provides fixed url'))

    creation_date = models.DateTimeField(
        verbose_name    = _('date of creation'),
        editable        = False, # hide from admin and form
        help_text       = _('autogenerated'),
        auto_now_add    = True)

    #moderators = models.ManyToManyField(
    #    to              = User,
    #    related_name    = 'moderatorOf',
    #    editable        = False) # hide from admin and form
    # USE USER GROUPS

    sponsors = models.ManyToManyField(
        to              = User,
        related_name    = 'sponsorOf',
        editable        = False) # hide from admin and form

    infavor = models.ManyToManyField(
        to              = User,
        related_name    = 'infavor',
        editable        = False) # hide from admin and form

    against = models.ManyToManyField(
        to              = User,
        related_name    = 'against',
        editable        = False) # hide from admin and form

    undecided = models.ManyToManyField(
        to              = User,
        related_name    = 'undecided',
        editable        = False) # hide from admin and form

    tags = models.ManyToManyField(
        to              = Tag,
        related_name    = 'tags')

    followers = models.ManyToManyField(
        to              = User,
        related_name    = 'follower',
        editable        = False) # hide from admin and form

    active = models.BooleanField(
        verbose_name    = _('active flag'),
        editable        = False, # hide from admin and form
        default         = False,
        help_text       = _('active flag'))

    restricted = models.BooleanField(
        verbose_name    = _('restricted'),
        default         = True,
        help_text       = _('restricted'))

    recruiting = models.BooleanField(
        verbose_name    = _('recruiting'),
        default         = False,
        help_text       = _('proposal is recruting moderators'))

    visitors = models.IntegerField(
        verbose_name    = _('number of visits'),
        editable        = False, # hide from admin and form
        default         = 0,
        help_text       = _('autopopulated'))

    related = models.ManyToManyField(
        to              = 'self',
        through         = 'Link',
        through_fields  = ('proposal', 'other'),
        symmetrical     = False, # required for a 'through' MtM
        editable        = False) # hide from admin and form

    def validate_title(self, value):
        if value.strip() == '':
            logger.info("trying to enter a proposal with empty title")
            raise ValidationError(_("Title is empty."))

    def save(self, *args, **kwargs):
        if not self.id:
            # newly created object
            self.title = self.title[0:1].capitalize() + self.title[1:]
            self.slug = slugify(unidecode(self.title))[:140]
            U = User.objects.get(pk=1)
            c = Cover.objects.create(
                   creator = U)
            self.cover_root = c
            self.cover = c
            s = Synopsis.objects.create(
                   content = default_synopsis(),
                   comment = _('default content'),
                   creator = U)
            self.synopsis_root = s
            self.synopsis = s

        self.full_clean()
        super(Proposal, self).save(*args, **kwargs)

    class Meta:
        verbose_name = _('proposal')
        verbose_name_plural = _('proposals')

    def __str__(self):
        return self.title

class Relation(models.Model):
    label = models.CharField(
        verbose_name    = (_('status of link')),
        max_length      = 10,
        help_text       = _('status of link'))

    label_plural = models.CharField(
        verbose_name    = (_('status of link')),
        max_length      = 10,
        help_text       = _('status of link'))

    reverse_relation = models.ForeignKey('self')

    def __str__(self):
        return self.label

class Link(models.Model):
    other = models.ForeignKey(Proposal, related_name = 'referencedBy')
    proposal = models.ForeignKey(Proposal)
    date = models.DateTimeField(auto_now_add = True)
    user = models.ForeignKey(User)
    relation = models.ForeignKey(Relation)
    reverse_link = models.ForeignKey('self', null = True)

    def save(self, *args, **kwargs):
        self.full_clean()
        # correctly set reverse
        # todo

        return super(Link, self).save(*args, **kwargs)

    def delete(self, *args, **kwargs):
        # correctly reset reverse
        # todo

        return super(Link, self).delete(*args, **kwargs)

    def __str__(self):
        c = '<->' if self.reverse_link else ' ->'
        return '%(source)s %(connector)s (%(relation)s) %(connector)s %(destination)s' % {
                'source': self.proposal.title,
                'connector': c,
                'relation': self.relation.label,
                'destination': self.other.title}

def default_synopsis():
    return _(
"""# This proposal does not have a detailed description yet.

You are reading the default text associated with each new proposal. Read further to learn more about what to do next!

The title of the proposal is set in stone and cannot change. This text, on the contrary, is here to evolve and mature at the same pace that your proposal is enriched by time and the contributions of other users.

## Edit this text now to provide further information:
* *key figures*,
* elements for *debate*,
* *links* to interesting resource
* etc, ...

## The next steps could be:
* choose who can *participate*
* define a *charter*
* hire *moderators*
* *promote* your idea
* *link* related proposals
* etc, etc, ...

## The weekly life cycle:

Proposals made on SITE NAME follow a weekly life cycle. The week runs from Tuesday 12am to the next Monday at midnight. At the end of the week, the statistics of each proposal are gathered and updated:

* The number of votes in favor, against or undecided, is computed and published on the statistics page
* The number of POKE received during the week is also counted, and the top scoring proposals make it to the leader's score board for that week

The proposal scoring the most during a given week will receive a special promotion the following week! Make sure you gather as many pokes as you can, through advertisement and promotion of your idea.

On the other hand, any proposal that does not receive any POKE during an entire week, will meet a terrible fate and 'die'. The abandonned proposals will turn to read-only mode, and no one, creator included, will be able to modify or comment further. But hope is permitted: anyone, at any time, can clone a proposal, and become the new supporter of an idea."""
)

proposal/views.py
from django.shortcuts import render
from django.shortcuts import get_object_or_404
from django.http import HttpResponseBadRequest
from django.http import HttpResponseRedirect
from django.shortcuts import redirect
from proposal.models import Proposal, Relation, Link
from django.contrib.auth.models import User
from control.views import get_control_form, apply_control_form
from place.utils import get_breadcrumbs
from django.core.urlresolvers import reverse
import operator
from django.db.models import Q
from django.utils.translation import ungettext
from functools import reduce
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
import  place.views
import agora.views
import logging

logger = logging.getLogger(__name__)

def shortcut(request, pk):
    p = get_object_or_404(Proposal, pk=pk)
    return HttpResponseRedirect(reverse('proposal:content',
                                       kwargs = { 'pk': pk, 'slug': p.slug }))

def common(request, pk, slug):
    c = {}
    if request.method == 'POST':
        if not request.user.is_authenticated():
           return (c, redirect("%s?next=%s" % (reverse('account:login'), request.path)))
        if not apply_control_form(request):
            return (c, HttpResponseBadRequest("Bad request"))

    p = get_object_or_404(Proposal, pk=pk)
    if slug != p.slug:
       return (c, HttpResponseRedirect(reverse('proposal:content',
                                       kwargs = { 'pk': pk, 'slug': p.slug })))

    c['p'] = p
    c['control_form'] = get_control_form(p, request.user)
    c['control_callback'] = request.path_info
    c['breadcrumbs'] = get_breadcrumbs(p.place)
    c['searchbox'] = agora.views.searchform(request)
    return (c, None)

def discuss(request, pk, slug):
    (context, error) = common(request, pk, slug)
    if error:
        return error

    return render(request, 'proposal/discuss.html', context)

def statistics(request, pk, slug):
    (context, error) = common(request, pk, slug)
    if error:
        return error

    return render(request, 'proposal/statistics.html', context)

def reference(request, pk, slug):
    (context, error) = common(request, pk, slug)
    if error:
        return error

    return render(request, 'proposal/reference.html', context)

def charter(request, pk, slug):
    (context, error) = common(request, pk, slug)
    if error:
        return error

    return render(request, 'proposal/charter.html', context)

def content(request, pk, slug):
    (context, error) = common(request, pk, slug)
    if error:
        return error

    counters = []
    p = context['p']
    c = p.infavor.count()
    counters.append({ 'label': ungettext('in favor', 'in favor', c), 'count': c, 'url': None})
    c = p.against.count()
    counters.append({ 'label': ungettext('against', 'against', c), 'count': c, 'url': None })
    c = p.undecided.count()
    counters.append({ 'label': ungettext('undecided', 'undecided', c), 'count': c, 'url': None })
    c = p.followers.count()
    counters.append({ 'label': ungettext('follower', 'followers', c), 'count': c, 'url': None })
    c = p.visitors
    counters.append({ 'label': ungettext('visitor', 'visitors', c), 'count': c, 'url': None })

    for r in Relation.objects.all():
        label = r.label
        labels = r.label_plural

        # bidirectional relations
        q = Link.objects.filter(Q(proposal = p) &
                                Q(relation = r) &
                                ~Q(reverse_link = None))
        c = q.count()
        if c:
            if c == 1:
                o = q.first().other
                url = reverse('proposal:content',
                                    kwargs = {'pk': o.pk, 'slug': o.slug })
            else:
                url = "%s?ps=%s&pr=%s&pb=0" % (reverse('listing:standard'),
                                                p.pk, r.pk)
            counters.append({ 'label': ungettext(label, labels, c) + " (bidir)",
                              'count': c,
                              'url': url })

        # outgoing relations (pb=1)
        q = Link.objects.filter(proposal = p,
                                relation = r,
                                reverse_link = None)
        c = q.count()
        if c:
            if c == 1:
                o = q.first().other
                url = reverse('proposal:content',
                                    kwargs = {'pk': o.pk, 'slug': o.slug })
            else:
                url = "%s?ps=%s&pr=%s&pb=1" % (reverse('listing:standard'),
                                                p.pk, r.pk)
            counters.append({ 'label': ungettext(label, labels, c) + " (out)",
                              'count': c,
                              'url': url })

        # incoming relations (pb=1)
        q = Link.objects.filter(other = p,
                                relation = r.reverse_relation,
                                reverse_link = None)
        c = q.count()
        if c:
            if c == 1:
                o = q.first().proposal
                url = reverse('proposal:content',
                                    kwargs = {'pk': o.pk, 'slug': o.slug })
            else:
                url = "%s?pS=%s&pR=%s&pB=1" % (reverse('listing:standard'),
                                                p.pk, r.reverse_relation.pk)
            counters.append({ 'label': ungettext(label, labels, c) + " (in)",
                              'count': c,
                              'url': url })

    context['counters'] = counters
    return render(request, 'synopsis/content.html', context)

proposal/templates/proposal/charter.html
{% extends "proposal/main.html" %}

{% block proposal_content %}

<div class="p_charter">
    charter todo
</div>

{% endblock %}

proposal/templates/proposal/discuss.html
{% extends "proposal/main.html" %}

{% block proposal_content %}

<div class="p_discuss">
    discussion todo
</div>

{% endblock %}

proposal/templates/proposal/main.html
{% extends 'agora/content.html' %}
{% block content %}

{% load i18n %}

<div class="p_frame">
    <div class="p_sponsor">
        {% include 'proposal/sponsors.html' %}
    </div>
    <div class="p_header">
        <div class="p_title">
            {% include 'proposal/title.html' %}
        </div>
        <div class="p_place">
            {% include 'place/breadcrumb.html' %}
        </div>
        <div class="p_picture">
            {% include 'cover/insert.html' %}
            <p><a href="{% url 'proposal:cover:view' pk=p.pk slug=p.slug %}">{% trans "edit" %}</a></p>
        </div>
        <div class="p_sponsor">
            {% include 'proposal/sponsors.html' %}
        </div>
        <div class="p_control">
            {% include 'control/control.html' %}
        </div>
        <div class="p_status">
            {% include 'proposal/status.html' %}
        </div>
        <div class="p_moderators">
            {% include 'proposal/moderators.html' %}
        </div>
        <div class="p_tags">
            {% include 'tag/list.html' %}
            <p><a href="{% url 'proposal:tag:view' pk=p.pk slug=p.slug %}">{% trans "edit" %}</a></p>
        </div>
        <div class="p_meta">
            {% include 'proposal/meta.html' %}
        </div>
        <div class="p_menu">
            {% include 'proposal/menu.html' %}
        </div>
    </div>
    <div class="p_content">
        {% block proposal_content %}
        {% endblock %}
    </div>
</div>

{% endblock %}

proposal/templates/proposal/menu.html
{% load i18n %}

<p>
    <span>{% trans "shortcuts:" %}</span>
    <ul>
        <li>
            <a href="{% url 'proposal:content' pk=p.pk slug=p.slug %}">
                {% trans "home" %}
            </a>
        </li>
        <li>
            <a href="{% url 'proposal:discuss' pk=p.pk slug=p.slug %}">
                {% trans "discuss" %}
            </a>
        </li>
        <li>
            <a href="{% url 'proposal:reference' pk=p.pk slug=p.slug %}">
                {% trans "reference" %}
            </a>
        </li>
        <li>
            <a href="{% url 'proposal:charter' pk=p.pk slug=p.slug %}">
                {% trans "charter" %}
            </a>
        </li>
        <li>
            <a href="{% url 'proposal:statistics' pk=p.pk slug=p.slug %}">
                {% trans "statistics" %}
            </a>
        </li>
        <li>
            {% trans "share" %}
        </li>
        <li>
            {% trans "clone" context "verb" %}
        </li>
        <li>
            {% trans "sponsor" context "verb" %}
        </li>
        {% if p.recruiting %}
            <li>
                {% trans "we are recruiting moderators" %}
            </li>
        {% endif %}
    </ul>
</p>

proposal/templates/proposal/meta.html
{% load humanize %}
{% load i18n %}

<p>
    <span>{% trans "status:" %}</span>
    <ul class="meta_entries">
        {% for c in counters %}
            <li>
                {% if c.url %}
                    <a href="{{ c.url }}">
                        {{ c.label }}
                        {{ c.count|intcomma }}
                    </a>
                {% else %}
                    {{ c.label }}
                    {{ c.count|intcomma }}
                {% endif %}
            </li>
        {% endfor %}
    </ul>
</p>

proposal/templates/proposal/moderators.html
{% load usertags %}
{% load i18n %}

{% if p.moderators.exists %}

<p>
    <span class="moderator_label">{% blocktrans count cnt=p.moderators.all.count %}moderator{% plural %}moderators{% endblocktrans %}</span>
    <ul class="moderator_entries">
        {% for s in p.moderators.all %}
            <li {% if forloop.last %} class='last'{% endif %}>
                {% getuserlink s p %}
                {{ userlink }}
            </li>
        {% endfor %}
    </ul>
</p>

{% endif %}

proposal/templates/proposal/reference.html
{% extends "proposal/main.html" %}

{% block proposal_content %}

<div class="p_reference">
    reference todo
</div>

{% endblock %}

proposal/templates/proposal/sponsors.html
{% if p.sponsors.exists %}

{% load usertags %}
{% load i18n %}

<p><span class="sponsor_label">{% trans "Proposal sponsored by" %}</span>
<ul class="sponsor_entries">
    {% for s in p.sponsors.all %}
        <li {% if forloop.last %} class='last'{% endif %}>
            {% getuserlink s p %}
            {{ userlink }}
        </li>
    {% endfor %}
</ul></p>

{% endif %}

proposal/templates/proposal/statistics.html
{% extends "proposal/main.html" %}

{% block proposal_content %}

<div class="p_statistics">
    stats todo
</div>

{% endblock %}

proposal/templates/proposal/status.html
{% load usertags %}
{% load i18n %}
{% load humanize %}

{% getuserlink p.creator p %}
<p class="p_status_creator">
    {% blocktrans with date=p.creation_date|date:"DATE_FORMAT" %}Proposal created by {{ userlink }} on {{ date }}.{% endblocktrans %}
</p>

{% if not p.active %}

    <p class="p_status_inactive">
        {% trans "This proposal is deactivated." %}
    </p>

{% endif %}

proposal/templates/proposal/title.html
<h3>{{ p.title }}</h3>