agora/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
# for dev only:
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = patterns('',
    url(r'^$',  'agora.views.home', name='home'),
    url(r'^s/', 'agora.views.search', name='search'),
    url(r'^a/', include('listing.urls', namespace='listing')),
    url(r'^p/(?P<pk>\d+)/', include('proposal.urls', namespace='proposal')),
    url(r'^l/(?P<place>\d+)/', include('place.urls', namespace='place')),
    url(r'^t/(?P<tag>\d+)/', include('tag.urls', namespace='tag')),
    url(r'^u/', include('account.urls', namespace='account')),
    url(r'^g/', include('germ.urls', namespace='germ')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^markdown/$', 'synopsis.views.markdown', name='markdown'),
    url(r'^m/$', 'django_markdown.views.preview', name='django_markdown_preview')
) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

proposal/urls.py
from django.conf.urls import patterns, include, url

urlpatterns_slug = patterns('proposal.views',
    url(r'^$', 'content', name='content'),
    url(r'^d/$', 'discuss', name='discuss'),
    url(r'^r/$', 'reference', name='reference'),
    url(r'^s/$', 'statistics', name='statistics'),
    url(r'^c/$', 'charter', name='charter'),
    url(r'^h/', include('synopsis.urls', namespace='synopsis')),
    url(r'^t/', include('tag.urls_proposal', namespace='tag')),
    url(r'^i/', include('cover.urls', namespace='cover')))

urlpatterns = patterns('proposal.views',
    url(r'^(?P<slug>[-\w]+)/', include(urlpatterns_slug)),
    url(r'^$', 'shortcut', name='shortcut'))

synopsis/urls.py
from django.conf.urls import patterns, include, url

urlpatterns = patterns('synopsis.views',
    url(r'^$', 'view', name='view'),
    url(r'^a/$', 'add', name='add'),
    url(r'^s/(?P<synopsis>\d+)/$', 'select', name='select'),
    url(r'^d/(?P<synopsis>\d+)/$', 'delete', name='delete'),
    url(r'^v/(?P<synopsis>\d+)/$', 'single', name='single'))

tag/urls.py
from django.conf.urls import patterns, url

urlpatterns = patterns('tag.views',
    url(r'^(?P<slug>[-\w]+)/$', 'list', name='list'),
    url(r'^$', 'shortcut', name='shortcut'),
)

synopsis/models.py
from django.db import models
from django.contrib.auth.models import User
from agora.models import DeletedContent
from django_markdown.models import MarkdownField
from django.utils.translation import ugettext_lazy as _
from mptt.models import MPTTModel, TreeForeignKey

class Synopsis(MPTTModel):
    parent = TreeForeignKey('self',
        null            = True,
        blank           = True,
        related_name    = 'children')

    content = MarkdownField()

    creator = models.ForeignKey(
        to              = User,
        related_name    = 'redactorOf')

    creation_date = models.DateTimeField(
        auto_now_add    = True)

    deleted = models.OneToOneField(
        to              = DeletedContent,
        null            = True,
        blank           = True)

synopsis/forms.py
from django import forms
from agora.forms import ModifyForm
from django_markdown.fields import MarkdownFormField
from django.utils.translation import ugettext_lazy as _
import logging

logger = logging.getLogger(__name__)

class AddForm(ModifyForm):
    content = MarkdownFormField()

synopsis/views.py
from django.shortcuts import render
from django.shortcuts import get_object_or_404
from django.http import HttpResponseBadRequest
from django.http import HttpResponseRedirect
from django.contrib.auth.decorators import login_required
import logging
from proposal.models import Proposal
from .models import Synopsis
from agora.forms import ModifyForm
from .forms import AddForm
from django.core.urlresolvers import reverse
from django.db import transaction
from django.utils.translation import ugettext as _
from agora.models import DeletedContent, DeletedReason
from agora.views import searchform

logger = logging.getLogger(__name__)

@login_required
def view(request, pk, slug):
    searchbox = searchform(request)
    p = get_object_or_404(Proposal, pk=pk)

    # reload object from DB to ensure mptt tree sync
    # TODO use select_related
    s = get_object_or_404(Synopsis, pk=p.synopsis_root.pk)
    synopsia = s.get_descendants(include_self = True)

    popup_title = _("Edition of the synopsis")
    return render(request, 'synopsis/view.html', locals())

@login_required
def select(request, pk, slug, synopsis):
    searchbox = searchform(request)
    p = get_object_or_404(Proposal, pk=pk)
    s = get_object_or_404(Synopsis, pk=synopsis)
    if (s.tree_id != p.synopsis_root.tree_id or
        s.deleted or p.synopsis == s):
        return HttpResponseBadRequest("Bad request")

    if request.method == 'POST':
        if 'select' in request.POST:
            form = ModifyForm(request.POST)
            if not form.is_valid():
                return render(request, 'synopsis/select.html', locals())

            with transaction.atomic():
                p.synopsis = s
                p.save()

        return HttpResponseRedirect(reverse('proposal:synopsis:view',
                                   kwargs = { 'pk': pk, 'slug': slug }))

    form = ModifyForm()
    return render(request, 'synopsis/select.html', locals())

@login_required
def add(request, pk, slug):
    searchbox = searchform(request)
    p = get_object_or_404(Proposal, pk=pk)

    if request.method == 'POST':
        if 'add' in request.POST:
            form = AddForm(request.POST)
            if not form.is_valid():
                return render(request, 'synopsis/add.html', locals())

            with transaction.atomic():
                if p.synopsis.content != request.POST.get('content'):
                    s = Synopsis(content = request.POST.get('content'),
                                 creator = request.user)
                    # todo: log, as proof in case of issue
                    # todo: publish comment as message
                    o = get_object_or_404(Synopsis, pk=p.synopsis.pk
                                    ).get_descendants(include_self=True).last()
                    s.insert_at(o, save=True)
                    p.synopsis = s
                    p.save()

        return HttpResponseRedirect(reverse('proposal:synopsis:view',
                               kwargs = { 'pk': pk, 'slug': slug }))

    synopsis = request.GET.get('pk')
    if synopsis:
        s = get_object_or_404(Synopsis, pk=synopsis)
        if not s.tree_id == p.synopsis_root.tree_id or s.deleted:
            return HttpResponseBadRequest("Bad request")
        c = s.content
    else:
        c = ''

    form = AddForm(initial = { 'content': c })
    return render(request, 'synopsis/add.html', locals())

@login_required
def delete(request, pk, slug, synopsis):
    searchbox = searchform(request)
    p = get_object_or_404(Proposal, pk=pk)
    s = get_object_or_404(Synopsis, pk=synopsis)
    if (s.tree_id != p.synopsis.tree_id or
        s == p.synopsis_root or
        s.deleted):
        return HttpResponseBadRequest("Bad request")

    if request.method == 'POST':
        # Todo: only moderator can delete
        if 'delete' in request.POST:
            form = ModifyForm(request.POST)
            if not form.is_valid():
                return render(request, 'synopsis/delete.html', locals())

            with transaction.atomic():
                if p.synopsis == s:
                    p.synopsis = p.synopsis_root
                    p.save()
                r = DeletedReason.objects.get(label='other') #todo
                s.deleted = DeletedContent.objects.create(
                                reason = r,
                                user   = request.user)
                s.save()
                # todo: publish message

        return HttpResponseRedirect(reverse('proposal:synopsis:view',
                               kwargs = { 'pk': pk, 'slug': slug }))

    form = ModifyForm()
    return render(request, 'synopsis/delete.html', locals())

def markdown(request):
    return render(request, 'synopsis/help.html', locals())

@login_required
def single(request, pk, slug, synopsis):
    searchbox = searchform(request)
    p = get_object_or_404(Proposal, pk=pk)
    s = get_object_or_404(Synopsis, pk=synopsis)
    source = True if request.GET.get('src') else False
    if (not s in p.synopsis_root.get_descendants(include_self=True) or
            s.deleted):
        return HttpResponseBadRequest("Bad request")
    extend = 'agora/flat_popup.html'
    return render(request, 'synopsis/single.html', locals())

synopsis/templates/synopsis/add.html
{% extends 'synopsis/popup.html' %}
{% load i18n %}

{% block popup_subsubtitle %}{% trans "New synopsis" %}{% endblock %}

{% block popup_content %}


<form action="{% url 'proposal:synopsis:add' pk=pk slug=slug %}" method="post" novalidate enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.content }}
    <p>
    {% trans "help with format" as l %}
    <a href="{% url 'markdown' %}" title="{{ l }}" target="_blank">{{ l }}</a>
    </p>
    <div>
    <p>{{ form.message }}</p>
    {% if form.message.errors %}
        <p>{{ form.message.errors }}</p>
    {% endif %}
    </div>
    <input type="submit" name="add" value="{% trans "submit synopsis" %}" />
</form>
{% endblock %}

synopsis/templates/synopsis/content.html
{% extends "proposal/main.html" %}

{% block proposal_content %}

{% load i18n %}
{% load django_markdown %}

<p class="p_synopsis">
    {{ p.synopsis.content|markdown_safe }}
    <p><a href="{% url 'proposal:synopsis:view' pk=p.pk slug=p.slug %}">{% trans "edit" %}</a></p>
</p>

{% endblock %}

synopsis/templates/synopsis/delete.html
{% extends 'synopsis/popup.html' %}
{% load i18n %}

{% block popup_subsubtitle %}{% trans "Deletion" %}{% endblock %}

{% block popup_content %}

{% with synopsis=s truncate=50 %}
    {% include 'synopsis/item.html' %}
{% endwith %}

<form action="{% url 'proposal:synopsis:delete' pk=pk slug=slug synopsis=s.pk %}" method="post" novalidate>
    {% csrf_token %}
    <div>
    <p>{{ form.message }}</p>
    {% if form.message.errors %}
        <p>{{ form.message.errors }}</p>
    {% endif %}
    </div>
    <p><input type="submit" name="delete" value="{% trans "delete" %}" /></p>
</form>

{% endblock %}

synopsis/templates/synopsis/help.html
{% extends 'agora/flat.html' %}
{% block content %}

{% load i18n %}
{% load django_markdown %}

<div>
    {% filter markdown %}
        {% blocktrans %}
The edition language is based on Markdown. Below is the basic cheat sheet. Please refer to the official documentation at [link todo](link) for more.

# Headers

```# title```

# title


```## sub-title```

## sub-title


# Emphasis

```*italics*```

*italics*


```**bold**```

**bold**


# Lists

```1. First ordered list item```
```2. second item```

1. First ordered list item
2. second item

```* Unordered list item```
```* Unordered list item```

* Unordered list item
* Unordered list item


# Links

```[I'm an external link](https://www.google.com)```

[I'm an external link](https://www.google.com "optional title")

```[I'm an internal link to a proposal](/p/1)```

[I'm an internal link to a proposal](/p/1)

```[I'm a reference-style link][1]. Append the reference at the bottom of your paragraph or document.```
```[1]: /p/1```

[I'm a reference-style link][1]. Append the reference at the bottom of your paragraph or document.
[1]: /p/1 "title"


# Pictures

```Inline-style:```
```![alternative text](http://images.com/icon48.png "optional title")```

![alternative text](http://images.com/icon48.png "optional title")

```Reference-style:```
```![alternative text][image]```
``` ```
```[image]: http://images.com/icon48.png "optional title"```

![alternative text][image]
[image]: http://images.com/icon48.png "optional title"


# Quotes

```> Blockquotes are very handy for citations```

> Blockquotes are very handy for citations

```Inline `code` has `back-ticks around` it.```

Inline `code` has `back-ticks around` it.

``` ` ` `Code blocks have three back-ticks around it. ` ` ` ```

```Code blocks have three back-ticks around it.```


# Tables
```Colons can be used to align columns.```

```| header 1         | header 2      | Header 3  |```
```| ---------------- |:-------------:| ---------:|```
```| column 1 is      | left-aligned  |     $1600 |```
```| column 2 is      | centered      |       $12 |```
```| column 3 is      | right-aligned |     $1600 |```


| header 1         | header 2      | Header 3  |
| ---------------- |:-------------:| ---------:|
| column 1 is      | left-aligned  |     $1600 |
| column 2 is      | centered      |       $12 |
| column 3 is      | right-aligned |     $1600 |


# Line break

```Three consecutive dashes: --- produce a line break```

---


# Abbreviations

```The definition of abbreviations, such as PACA, can show up when the mouse hovers over the text.```
```*[PACA]: Provence-Alpes-Côte d'Azur```

The definition of abbreviations, such as PACA, can show up when the mouse hovers over the text.

*[PACA]: Provence-Alpes-Côte d'Azur


# Footnotes

```Use ^ in square brackets to create footnotes[^1].```

```[^1]: This is the footnote content; use the same label, brackets and a colon```

Use ^ in square brackets to create footnotes[^1].

[^1]: This is the footnote content; use the same label, brackets and a colon
        {% endblocktrans %}
    {% endfilter %}
</div>

{% endblock %}

synopsis/templates/synopsis/item.html
{% load i18n %}
{% load usertags %}

<div>
<p>
{% if synopsis == p.synopsis %}*{% endif %}
{% if s.deleted %}
     {% trans "deleted" %}
{% else %}
    {{ synopsis.content|truncatewords:truncate }}
{% endif %}
</p>

{% getuserlink synopsis.creator p %}
<p><small>{% blocktrans with creator=userlink cdate=synopsis.creation_date %}Edited by {{ creator }} on {{ cdate }}{% endblocktrans %}</small></p>
</div>

synopsis/templates/synopsis/popup.html
{% extends 'agora/flat_popup.html' %}
{% load i18n %}

{% block popup_title %}<a href="{% url 'proposal:content' pk=pk slug=slug %}" title="{{ p.title }}">{{ p.title }}</a>{% endblock %}

{% block popup_subtitle %}
{% trans "Synopsis management" as title %}
<a href="{% url 'proposal:synopsis:view' pk=pk slug=slug %}" title="{{ title }}">{{ title }}</a>
{% endblock %}

{% block popup_close %}{% url 'proposal:content' pk=pk slug=slug %}{% endblock %}

synopsis/templates/synopsis/select.html
{% extends 'synopsis/popup.html' %}
{% load i18n %}

{% block popup_subsubtitle %}{% trans "Selection" %}{% endblock %}

{% block popup_content %}

{% with synopsis=s truncate=50 %}
    {% include 'synopsis/item.html' %}
{% endwith %}

<form action="{% url 'proposal:synopsis:select' pk=pk slug=slug synopsis=s.pk %}" method="post" novalidate>
    {% csrf_token %}
    <div>
    <p>{{ form.message }}</p>
    {% if form.message.errors %}
        <p>{{ form.message.errors }}</p>
    {% endif %}
    </div>
    <p><input type="submit" name="select" value="{% trans "apply" %}" /></p>
</form>

{% endblock %}

synopsis/templates/synopsis/single.html
{% extends 'synopsis/popup.html' %}
{% load i18n %}
{% load usertags %}

{% block popup_subsubtitle %}{% trans "View" %}{% endblock %}

{% block popup_content %}

{% if source %}
{{ s.content }}
{% else %}
{% load django_markdown %}
{{ s.content|markdown }}
{% endif %}

{% getuserlink s.creator p %}
<p><small>{% blocktrans with creator=userlink cdate=s.creation_date %}Edited by {{ creator }} on {{ cdate }}{% endblocktrans %}</small></p>

{% endblock %}

synopsis/templates/synopsis/view.html
{% extends 'synopsis/popup.html' %}
{% load i18n %}

{% block popup_subsubtitle %}{% trans "History" %}{% endblock %}

{% block popup_content %}
<p>
<a href="{% url 'proposal:synopsis:add' pk=pk slug=slug %}" title="new">new (start empty)</a>
</p>

<ul>
{% for s in synopsia reversed %}
    <li>
        {% with synopsis=s truncate=10 %}
            {% include 'synopsis/item.html' %}
        {% endwith %}
        {% if not s.deleted %}
            <ul>
            <li><a href="{% url 'proposal:synopsis:single' pk=pk slug=slug synopsis=s.pk %}" title="view this version">view</a></li>
            <li><a href="{% url 'proposal:synopsis:single' pk=pk slug=slug synopsis=s.pk %}?src=1" title="view source">view source</a></li>
            <li><a href="" title="differences with previous">view diff</a></li>
            {% trans "new from this version" as l %}
            <li><a href="{% url 'proposal:synopsis:add' pk=pk slug=slug %}?pk={{ s.pk }}" title="{{ l }}">{{ l }}</a></li>
            {% if s != p.synopsis %}
                <li><a href="{% url 'proposal:synopsis:select' pk=pk slug=slug synopsis=s.pk %}" title="select this version">select</a></li>
            {% endif %}
            {% if s != p.synopsis_root %}
                <li><a href="{% url 'proposal:synopsis:delete' pk=pk slug=slug synopsis=s.pk %}" title="delete this version">delete</a></li>
            {% endif %}
            </ul>
        {% endif %}
    </li>
{% endfor %}
</ul>

{% endblock %}